on: push

jobs:  
  ci:  
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      packages: write

    steps:
       - uses:  actions/checkout@v4
       - uses: actions/setup-python@v5
         with: 
            python-version: "3.14.6"
       - run: pip install -r requirements.txt          

        #===== Container Test ======
       - name: Build  Docker image
         run: docker build -t task_api .

       - name: Create Docker network
         run: docker network create ci-network
      
       - name: PostreSQL container   
         run: |
            docker run -d \
            --name postgres \
            --network ci-network \
            -e POSTGRES_DB=taskdb \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_USER=postgres \
             postgres:17

       - name: Wait for PostgreSQL
         run: |
            until docker exec postgres pg_isready -U postgres -d taskdb; do
              sleep 2
            done

       - name: Start Django
         run: |
            docker run -d \
            --name django \
            --network ci-network \
            -p 8000:8000 \
            -e DATABASE_URL=postgresql://postgres:postgres@postgres:5432/taskdb \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            task_api

       - name: Wait for Django
         run: |
            until curl --output /dev/null --silent --head http://127.0.0.1:8000/; do
             sleep 2
             done
       - name: Run migration
         run: docker exec django python manage.py migrate --noinput

       - run: pytest

       - name: Show django logs
         if: always()
         run: docker logs django

       - name: Login to GHCR
         uses: docker/login-action@v3
         with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

       - name: Tag image
         run: docker tag task_api ghcr.io/${{ github.repository }}:latest

       - name: Push image
         run: docker push ghcr.io/${{ github.repository }}:latest


      

       
